@startuml
title Sensor Management Service Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


class SensorStateSubscriber {
  +void consume(byte[] payload)
}

class ServiceStatePublisher {
  +void publish(Sensor sensor)
}

class SensorControlPublisher {
  +void publish(SensorControlSignal signal)
}

class SensorDataController {
  +List<Sensor> all()
  +Sensor getSensor(Long id)
  +Sensor newSensor(Sensor sensor)
  +Sensor amendSensor(Long id, Sensor sensor)
  +void deleteSensor(Long id)
}

class SensorCommandController {
  +void commandDo(Command command)
}

class UserVerificationClient {
  +boolean isValid(String jwt)
}

class TelemetryServiceClient {
  +void subscribe()
}

class Sensor {
}

class SensorRepository {
}

class SensorState {
}

class SensorControlSignal {
}

class Command {
}

@enduml